project:
  type: website
  output-dir: "../docs/"

website:
  title: "uvdev"
  page-navigation: true
  navbar:
    background: primary
    search: true
    right: 
      - icon: github
        href: "https://github.com/fligt/fix-uv-jupytext"
  sidebar:
    style: floating
    contents: auto
  page-footer: "2026 Rijkserfgoedlaboratorium Amsterdam"